### ISSUE TITLE
For Newcomers

### ISSUE THREAD

**Issue by Larrtroffen** [Larrtroffen/Stata_Guidebook#1]
# Issue指南
## 提问题
直接写哪个部分（标题）有问题，将您的想法或者您修改后的部分直接使用markdown进行上传即可。
## 提需求
直接讲你要实现哪个功能、跑哪张表（给出来源论文），即可。

**Comment by 18365615055** [comment]
哥哥最棒！

**Comment by xiaoyaoxinyi** [comment]
哥哥真厉害
